package co.edu.uniminuto.arqSw.Modelo;
// Generated 20-sep-2017 0:59:45 by Hibernate Tools 4.3.1



/**
 * ClientePorContenido generated by hbm2java
 */
public class ClientePorContenido  implements java.io.Serializable {


     private ClientePorContenidoId id;
     private Cliente cliente;
     private Contenido contenido;

    public ClientePorContenido() {
    }

    public ClientePorContenido(ClientePorContenidoId id, Cliente cliente, Contenido contenido) {
       this.id = id;
       this.cliente = cliente;
       this.contenido = contenido;
    }
   
    public ClientePorContenidoId getId() {
        return this.id;
    }
    
    public void setId(ClientePorContenidoId id) {
        this.id = id;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Contenido getContenido() {
        return this.contenido;
    }
    
    public void setContenido(Contenido contenido) {
        this.contenido = contenido;
    }




}


