package co.edu.uniminuto.arqSw.Modelo;
// Generated 20-sep-2017 0:59:45 by Hibernate Tools 4.3.1



/**
 * ClientePorValoracion generated by hbm2java
 */
public class ClientePorValoracion  implements java.io.Serializable {


     private ClientePorValoracionId id;
     private Cliente cliente;
     private Valoracion valoracion;

    public ClientePorValoracion() {
    }

    public ClientePorValoracion(ClientePorValoracionId id, Cliente cliente, Valoracion valoracion) {
       this.id = id;
       this.cliente = cliente;
       this.valoracion = valoracion;
    }
   
    public ClientePorValoracionId getId() {
        return this.id;
    }
    
    public void setId(ClientePorValoracionId id) {
        this.id = id;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Valoracion getValoracion() {
        return this.valoracion;
    }
    
    public void setValoracion(Valoracion valoracion) {
        this.valoracion = valoracion;
    }




}


