package co.edu.uniminuto.arqSw.Modelo;
// Generated 20-sep-2017 0:59:45 by Hibernate Tools 4.3.1



/**
 * ClientePorContenidoId generated by hbm2java
 */
public class ClientePorContenidoId  implements java.io.Serializable {


     private int idCliente;
     private int idContenido;

    public ClientePorContenidoId() {
    }

    public ClientePorContenidoId(int idCliente, int idContenido) {
       this.idCliente = idCliente;
       this.idContenido = idContenido;
    }
   
    public int getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(int idCliente) {
        this.idCliente = idCliente;
    }
    public int getIdContenido() {
        return this.idContenido;
    }
    
    public void setIdContenido(int idContenido) {
        this.idContenido = idContenido;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ClientePorContenidoId) ) return false;
		 ClientePorContenidoId castOther = ( ClientePorContenidoId ) other; 
         
		 return (this.getIdCliente()==castOther.getIdCliente())
 && (this.getIdContenido()==castOther.getIdContenido());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdCliente();
         result = 37 * result + this.getIdContenido();
         return result;
   }   


}


