package co.edu.uniminuto.arqSw.Modelo;
// Generated 20-sep-2017 0:59:45 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Coleccion generated by hbm2java
 */
public class Coleccion  implements java.io.Serializable {


     private Integer idColeccion;
     private Contenido contenido;
     private String volumen;
     private Set videos = new HashSet(0);

    public Coleccion() {
    }

	
    public Coleccion(Contenido contenido, String volumen) {
        this.contenido = contenido;
        this.volumen = volumen;
    }
    public Coleccion(Contenido contenido, String volumen, Set videos) {
       this.contenido = contenido;
       this.volumen = volumen;
       this.videos = videos;
    }
   
    public Integer getIdColeccion() {
        return this.idColeccion;
    }
    
    public void setIdColeccion(Integer idColeccion) {
        this.idColeccion = idColeccion;
    }
    public Contenido getContenido() {
        return this.contenido;
    }
    
    public void setContenido(Contenido contenido) {
        this.contenido = contenido;
    }
    public String getVolumen() {
        return this.volumen;
    }
    
    public void setVolumen(String volumen) {
        this.volumen = volumen;
    }
    public Set getVideos() {
        return this.videos;
    }
    
    public void setVideos(Set videos) {
        this.videos = videos;
    }




}


