package co.edu.uniminuto.arqSw.Modelo;
// Generated 20-sep-2017 0:59:45 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Contenido generated by hbm2java
 */
public class Contenido  implements java.io.Serializable {


     private Integer idContenido;
     private Proveedor proveedor;
     private String isan;
     private String titulo;
     private String descripcion;
     private Set series = new HashSet(0);
     private Video video;
     private Set clientePorContenidos = new HashSet(0);
     private Set coleccions = new HashSet(0);

    public Contenido() {
    }

	
    public Contenido(Proveedor proveedor, String isan, String titulo, String descripcion) {
        this.proveedor = proveedor;
        this.isan = isan;
        this.titulo = titulo;
        this.descripcion = descripcion;
    }
    public Contenido(Proveedor proveedor, String isan, String titulo, String descripcion, Set series, Video video, Set clientePorContenidos, Set coleccions) {
       this.proveedor = proveedor;
       this.isan = isan;
       this.titulo = titulo;
       this.descripcion = descripcion;
       this.series = series;
       this.video = video;
       this.clientePorContenidos = clientePorContenidos;
       this.coleccions = coleccions;
    }
   
    public Integer getIdContenido() {
        return this.idContenido;
    }
    
    public void setIdContenido(Integer idContenido) {
        this.idContenido = idContenido;
    }
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
    public String getIsan() {
        return this.isan;
    }
    
    public void setIsan(String isan) {
        this.isan = isan;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getSeries() {
        return this.series;
    }
    
    public void setSeries(Set series) {
        this.series = series;
    }
    public Video getVideo() {
        return this.video;
    }
    
    public void setVideo(Video video) {
        this.video = video;
    }
    public Set getClientePorContenidos() {
        return this.clientePorContenidos;
    }
    
    public void setClientePorContenidos(Set clientePorContenidos) {
        this.clientePorContenidos = clientePorContenidos;
    }
    public Set getColeccions() {
        return this.coleccions;
    }
    
    public void setColeccions(Set coleccions) {
        this.coleccions = coleccions;
    }




}


