package co.edu.uniminuto.arqSw.Modelo;
// Generated 20-sep-2017 0:59:45 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Serie generated by hbm2java
 */
public class Serie  implements java.io.Serializable {


     private Integer idSerie;
     private Contenido contenido;
     private String temporada;
     private Set videos = new HashSet(0);

    public Serie() {
    }

	
    public Serie(Contenido contenido, String temporada) {
        this.contenido = contenido;
        this.temporada = temporada;
    }
    public Serie(Contenido contenido, String temporada, Set videos) {
       this.contenido = contenido;
       this.temporada = temporada;
       this.videos = videos;
    }
   
    public Integer getIdSerie() {
        return this.idSerie;
    }
    
    public void setIdSerie(Integer idSerie) {
        this.idSerie = idSerie;
    }
    public Contenido getContenido() {
        return this.contenido;
    }
    
    public void setContenido(Contenido contenido) {
        this.contenido = contenido;
    }
    public String getTemporada() {
        return this.temporada;
    }
    
    public void setTemporada(String temporada) {
        this.temporada = temporada;
    }
    public Set getVideos() {
        return this.videos;
    }
    
    public void setVideos(Set videos) {
        this.videos = videos;
    }




}


