package co.edu.uniminuto.arqSw.Modelo;
// Generated 20-sep-2017 0:59:45 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Transaccion generated by hbm2java
 */
public class Transaccion  implements java.io.Serializable {


     private Integer idTransaccion;
     private Cliente cliente;
     private MedioPago medioPago;
     private Date fechaTransaccion;
     private String tipoTransaccion;

    public Transaccion() {
    }

    public Transaccion(Cliente cliente, MedioPago medioPago, Date fechaTransaccion, String tipoTransaccion) {
       this.cliente = cliente;
       this.medioPago = medioPago;
       this.fechaTransaccion = fechaTransaccion;
       this.tipoTransaccion = tipoTransaccion;
    }
   
    public Integer getIdTransaccion() {
        return this.idTransaccion;
    }
    
    public void setIdTransaccion(Integer idTransaccion) {
        this.idTransaccion = idTransaccion;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public MedioPago getMedioPago() {
        return this.medioPago;
    }
    
    public void setMedioPago(MedioPago medioPago) {
        this.medioPago = medioPago;
    }
    public Date getFechaTransaccion() {
        return this.fechaTransaccion;
    }
    
    public void setFechaTransaccion(Date fechaTransaccion) {
        this.fechaTransaccion = fechaTransaccion;
    }
    public String getTipoTransaccion() {
        return this.tipoTransaccion;
    }
    
    public void setTipoTransaccion(String tipoTransaccion) {
        this.tipoTransaccion = tipoTransaccion;
    }




}


