package co.edu.uniminuto.arqSw.Modelo;
// Generated 20-sep-2017 0:59:45 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Valoracion generated by hbm2java
 */
public class Valoracion  implements java.io.Serializable {


     private Integer idValoracion;
     private Video video;
     private String valoracion;
     private Set clientePorValoracions = new HashSet(0);

    public Valoracion() {
    }

	
    public Valoracion(Video video, String valoracion) {
        this.video = video;
        this.valoracion = valoracion;
    }
    public Valoracion(Video video, String valoracion, Set clientePorValoracions) {
       this.video = video;
       this.valoracion = valoracion;
       this.clientePorValoracions = clientePorValoracions;
    }
   
    public Integer getIdValoracion() {
        return this.idValoracion;
    }
    
    public void setIdValoracion(Integer idValoracion) {
        this.idValoracion = idValoracion;
    }
    public Video getVideo() {
        return this.video;
    }
    
    public void setVideo(Video video) {
        this.video = video;
    }
    public String getValoracion() {
        return this.valoracion;
    }
    
    public void setValoracion(String valoracion) {
        this.valoracion = valoracion;
    }
    public Set getClientePorValoracions() {
        return this.clientePorValoracions;
    }
    
    public void setClientePorValoracions(Set clientePorValoracions) {
        this.clientePorValoracions = clientePorValoracions;
    }




}


