package co.edu.uniminuto.arqSw.Modelo;
// Generated 20-sep-2017 0:59:45 by Hibernate Tools 4.3.1



/**
 * VideoPorPersona generated by hbm2java
 */
public class VideoPorPersona  implements java.io.Serializable {


     private VideoPorPersonaId id;
     private Persona persona;
     private Video video;

    public VideoPorPersona() {
    }

    public VideoPorPersona(VideoPorPersonaId id, Persona persona, Video video) {
       this.id = id;
       this.persona = persona;
       this.video = video;
    }
   
    public VideoPorPersonaId getId() {
        return this.id;
    }
    
    public void setId(VideoPorPersonaId id) {
        this.id = id;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public Video getVideo() {
        return this.video;
    }
    
    public void setVideo(Video video) {
        this.video = video;
    }




}


