package co.edu.uniminuto.arqSw.Modelo;
// Generated 20-sep-2017 0:59:45 by Hibernate Tools 4.3.1



/**
 * VideoPorPersonaId generated by hbm2java
 */
public class VideoPorPersonaId  implements java.io.Serializable {


     private int idPersona;
     private int idVideo;

    public VideoPorPersonaId() {
    }

    public VideoPorPersonaId(int idPersona, int idVideo) {
       this.idPersona = idPersona;
       this.idVideo = idVideo;
    }
   
    public int getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(int idPersona) {
        this.idPersona = idPersona;
    }
    public int getIdVideo() {
        return this.idVideo;
    }
    
    public void setIdVideo(int idVideo) {
        this.idVideo = idVideo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VideoPorPersonaId) ) return false;
		 VideoPorPersonaId castOther = ( VideoPorPersonaId ) other; 
         
		 return (this.getIdPersona()==castOther.getIdPersona())
 && (this.getIdVideo()==castOther.getIdVideo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdPersona();
         result = 37 * result + this.getIdVideo();
         return result;
   }   


}


