package co.edu.uniminuto.arqSw.Modelo;
// Generated 20-sep-2017 0:59:45 by Hibernate Tools 4.3.1



/**
 * VideoPorCategoria generated by hbm2java
 */
public class VideoPorCategoria  implements java.io.Serializable {


     private VideoPorCategoriaId id;
     private Categoria categoria;
     private Video video;

    public VideoPorCategoria() {
    }

    public VideoPorCategoria(VideoPorCategoriaId id, Categoria categoria, Video video) {
       this.id = id;
       this.categoria = categoria;
       this.video = video;
    }
   
    public VideoPorCategoriaId getId() {
        return this.id;
    }
    
    public void setId(VideoPorCategoriaId id) {
        this.id = id;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public Video getVideo() {
        return this.video;
    }
    
    public void setVideo(Video video) {
        this.video = video;
    }




}


