package co.edu.uniminuto.arqSw.Modelo;
// Generated 20-sep-2017 0:59:45 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Video generated by hbm2java
 */
public class Video  implements java.io.Serializable {


     private Integer idVideo;
     private Coleccion coleccion;
     private Contenido contenido;
     private Serie serie;
     private String yearProduccion;
     private String duracion;
     private String clasificacion;
     private int idContenido;
     private Set valoracions = new HashSet(0);
     private Set videoPorCategorias = new HashSet(0);
     private Set videoPorIdiomas = new HashSet(0);
     private Set videoPorPersonas = new HashSet(0);

    public Video() {
    }

	
    public Video(Coleccion coleccion, Contenido contenido, Serie serie, String yearProduccion, String duracion, String clasificacion, int idContenido) {
        this.coleccion = coleccion;
        this.contenido = contenido;
        this.serie = serie;
        this.yearProduccion = yearProduccion;
        this.duracion = duracion;
        this.clasificacion = clasificacion;
        this.idContenido = idContenido;
    }
    public Video(Coleccion coleccion, Contenido contenido, Serie serie, String yearProduccion, String duracion, String clasificacion, int idContenido, Set valoracions, Set videoPorCategorias, Set videoPorIdiomas, Set videoPorPersonas) {
       this.coleccion = coleccion;
       this.contenido = contenido;
       this.serie = serie;
       this.yearProduccion = yearProduccion;
       this.duracion = duracion;
       this.clasificacion = clasificacion;
       this.idContenido = idContenido;
       this.valoracions = valoracions;
       this.videoPorCategorias = videoPorCategorias;
       this.videoPorIdiomas = videoPorIdiomas;
       this.videoPorPersonas = videoPorPersonas;
    }
   
    public Integer getIdVideo() {
        return this.idVideo;
    }
    
    public void setIdVideo(Integer idVideo) {
        this.idVideo = idVideo;
    }
    public Coleccion getColeccion() {
        return this.coleccion;
    }
    
    public void setColeccion(Coleccion coleccion) {
        this.coleccion = coleccion;
    }
    public Contenido getContenido() {
        return this.contenido;
    }
    
    public void setContenido(Contenido contenido) {
        this.contenido = contenido;
    }
    public Serie getSerie() {
        return this.serie;
    }
    
    public void setSerie(Serie serie) {
        this.serie = serie;
    }
    public String getYearProduccion() {
        return this.yearProduccion;
    }
    
    public void setYearProduccion(String yearProduccion) {
        this.yearProduccion = yearProduccion;
    }
    public String getDuracion() {
        return this.duracion;
    }
    
    public void setDuracion(String duracion) {
        this.duracion = duracion;
    }
    public String getClasificacion() {
        return this.clasificacion;
    }
    
    public void setClasificacion(String clasificacion) {
        this.clasificacion = clasificacion;
    }
    public int getIdContenido() {
        return this.idContenido;
    }
    
    public void setIdContenido(int idContenido) {
        this.idContenido = idContenido;
    }
    public Set getValoracions() {
        return this.valoracions;
    }
    
    public void setValoracions(Set valoracions) {
        this.valoracions = valoracions;
    }
    public Set getVideoPorCategorias() {
        return this.videoPorCategorias;
    }
    
    public void setVideoPorCategorias(Set videoPorCategorias) {
        this.videoPorCategorias = videoPorCategorias;
    }
    public Set getVideoPorIdiomas() {
        return this.videoPorIdiomas;
    }
    
    public void setVideoPorIdiomas(Set videoPorIdiomas) {
        this.videoPorIdiomas = videoPorIdiomas;
    }
    public Set getVideoPorPersonas() {
        return this.videoPorPersonas;
    }
    
    public void setVideoPorPersonas(Set videoPorPersonas) {
        this.videoPorPersonas = videoPorPersonas;
    }




}


