package co.edu.uniminuto.arqSw.Modelo;
// Generated 20-sep-2017 0:59:45 by Hibernate Tools 4.3.1



/**
 * VideoPorCategoriaId generated by hbm2java
 */
public class VideoPorCategoriaId  implements java.io.Serializable {


     private int idVideo;
     private int idCategoria;

    public VideoPorCategoriaId() {
    }

    public VideoPorCategoriaId(int idVideo, int idCategoria) {
       this.idVideo = idVideo;
       this.idCategoria = idCategoria;
    }
   
    public int getIdVideo() {
        return this.idVideo;
    }
    
    public void setIdVideo(int idVideo) {
        this.idVideo = idVideo;
    }
    public int getIdCategoria() {
        return this.idCategoria;
    }
    
    public void setIdCategoria(int idCategoria) {
        this.idCategoria = idCategoria;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VideoPorCategoriaId) ) return false;
		 VideoPorCategoriaId castOther = ( VideoPorCategoriaId ) other; 
         
		 return (this.getIdVideo()==castOther.getIdVideo())
 && (this.getIdCategoria()==castOther.getIdCategoria());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdVideo();
         result = 37 * result + this.getIdCategoria();
         return result;
   }   


}


